[project]
name = "R1_LinearRegression"
version = "0.1.0"
description = "Example of LinearRegression Screener"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "backtrader-next>=2.3.3",
    "bn_quik>=1.1.0",
]

